name: Py-Spy Performance Profiling

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-profiling:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust this to match your project's Python version

      # Step 3: Install Py-Spy
      - name: Install Py-Spy
        run: |
          python -m pip install --upgrade pip
          pip install py-spy

      # Step 4: Run Py-Spy Profiling
      - name: Run Py-Spy Profiling
        run: |
          py-spy record -o pyspy_profile.svg -- python korok_seed_guide/Tests/test_credits.py
        # Ensure the path to 'test_credits.py' is correct relative to the repository root.
        # Adjust 'Tests/test_credits.py' if the script is located elsewhere.

      # Step 5: Upload Py-Spy Report
      - name: Upload Py-Spy Report
        uses: actions/upload-artifact@v3
        with:
          name: py-spy-profile
          path: pyspy_profile.svg
