name: Py-Spy Performance Profiling

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-profiling:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust this to match your project's Python version

      # Step 3: Install Py-Spy
      - name: Install Py-Spy
        run: |
          python -m pip install
