name: PyMX Performance Profiling

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-profiling:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Replace with your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymx
          pip install -r requirements.txt  # If applicable

      # Step 4: Run PyMX on the code
      - name: Run PyMX Profiling
        run: |
          pymx run test_credits.py --output-format html --output-file pymx-report.html

      # Step 5: Upload PyMX report
      - name: Upload PyMX Report
        uses: actions/upload-artifact@v3
        with:
          name: pymx-report
          path: pymx-report.html
