name: Python Testing

on:
  push:
    branches:
      - main
      - feature/*
      - dev
  pull_request:
    branches:
      - main
      - feature/*
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        # Ensure the test-results directory exists
        mkdir -p test-results
        # Run pytest and save results to test-results/results.xml
        pytest korok_guide_seeds/Tests/ --junitxml=test-results/results.xml || true

    - name: Upload test results
      if: always()  # Always try to upload results, even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results  # Path to the test results folder
