name: Python Testing

# Trigger the workflow on push and pull requests to any branch
on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
      - Dev

jobs:
  test:
    runs-on: ubuntu-latest  # Run the job on the latest version of Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version for testing
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install pytest  # Install pytest for running the tests
    
    - name: Run tests
      run: |
        pytest  # Run the tests using pytest
        
    - name: Upload test results
      if: failure()  # Only upload test results if the tests fail
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results  # Path to the test results folder 
